package com.gdsc.ganeshmandal

data class MandalFinalAudit(
    var auditId: String,
    var pointsElectricalCabling :String,
    var pointsElectricalTerminations :String,
    var pointsSwitchBoardInstallation :String,
    var pointsLocationOfFireExtinguishers :String,
    var pointsValidityOfFireExtinguishers :String,
    var pointsOtherFireSafetyArrangements :String,
    var pointsOperationOfMetalDetectors :String,
    var pointsOperationOfBombDetectors :String,
    var pointsSurveillanceCoverage :String,
    var pointsSurveillanceMonitoring :String,
    var pointsPublicAddressCoverage :String,
    var pointsAnnouncingTeam :String,
    var pointsLocationOfBanners :String,
    var pointsMedicalEmergencyMitigation :String,
    var pointsSecurityAndVolunteerTeam :String,
    var pointsCompetencyOfTeam :String,
    var pointsEmergencyEvacuationProcess :String,
    var pointsProactivenessOfFireSafety :String,
    var pointsIsMandalInsured :String,
    var totalScoreText :String,
    //
    var imgElectricalCabling :String,
    var imgElectricalTerminations :String,
    var imgSwitchBoardInstallation :String,
    var imgLocationOfFireExtinguishers :String,
    var imgValidityOfFireExtinguishers :String,
    var imgOtherFireSafetyArrangements :String,
    var imgOperationOfMetalDetectors :String,
    var imgOperationOfBombDetectors :String,
    var imgSurveillanceCoverage :String,
    var imgSurveillanceMonitoring :String,
    var imgPublicAddressCoverage :String,
    var imgAnnouncingTeam :String,
    var imgLocationOfBanners :String,
    var imgMedicalEmergencyMitigation :String,
    var imgSecurityAndVolunteerTeam :String,
    var imgCompetencyOfTeam :String,
    var imgEmergencyEvacuationProcess :String,
    var imgProactivenessOfFireSafety :String,
    var imgIsMandalInsured :String
)
