package com.gdsc.ganeshmandal

data class Mandal(
    val mandalId: String,
    val nameOfMandal: String,
    val addOfMandal: String,
    val contactPerson: String,
    val mobileNo: String,
    val totalAreaCovered: String,
    val totalAreaOpen: String,
    val dateOfTechnicalEvaluation: String,
    val powerConsumedByMandal: String,
    val sizeOfCableInstalled : String,
    val typeOfCable : String,
    val mcb_mccbInstalled : String,
    val _24ElectricianYesOrNo: String,
    val properTerminationOfCables: String,
    val fireExtin1 : String,
    val fireExt1Quant : String,
    val fireExtin2 : String,
    val fireExt2Quant : String,
    val fireDetect1 : String,
    val fireDetect1Quant : String,
    val fireDetect2 : String,
    val fireDetect2Quant : String,
    val typeOfCamera1 : String,
    val typeOfCamera1Qty : String,
    val typeOfCamera2 : String,
    val typeOfCamera2Qty : String,
    val dvr : String,
    val channels : String,
    val dvrQuantity : String,
    val storageDetails : String,
    val monitoringMethodology : String,
    val typeOfSpeaker1 : String,
    val typeOfSpeaker1Quant : String,
    val typeOfSpeaker2 : String,
    val typeOfSpeaker2Quant : String,
    val announcingTeam : String,
    val announcingTeamQuant : String,
    val typeOfDetector1 : String,
    val typeOfDetector1Quant : String,
    val typeOfDetector2 : String,
    val typeOfDetector2Quant : String,
    val typeOfSign1 : String,
    val typeOfSign1Quant : String,
    val typeOfSign2 : String,
    val typeOfSign2Quant : String,
    val firstAidKit : String,
    val firstAidKitQuant : String,
    val emergencyEvacuationPlanDetails : String,
    val securityTeamDetails : String,
    val trainingSecurityTeam : String,
    val remarks : String,
    val nameOfFSAIRepresentative: String,
    val nameOfMandalRepresentative: String,
    val firstAuditStatus: String,
    val secondAuditStatus: String,
    val MCBInstalledYesorNo: String,
    val FireExtinguishersYesorNo: String,
    val FireDetectorsYesorNo: String,
    val CCTVCameraYesorNo: String,
    val PublicAddressYesorNo: String,
    val MetalAndBombYesorNo: String,
    val FirstAidYesorNo: String,
    val EmergencyTeamYesorNo: String
)
